name = input("What is your name? ")
age = input("How old are you? ")
status = input("Are you married? ")
city = input("Which city do you live in? ")
country = input("What is name of your country? ")
profession = input("What is your profession? ")
hobby = input("What is your hobby? ")
print("Nice to meet you,", name + "!")
print("You are", age, "years old.")
print("Married:", status)
print("You live in", city + ",", country + ".")
print("Your profession is", profession)
print("Your hobby is", hobby)
print("Welcome to your Python journey!")