a = bool("hello")
b = bool("")
c = bool(0)
d = bool(77)
e = bool([])
print(a)
print(b)
print(c)
print(d)
print(e)
name = "Borz"
if name:
    print("Hello", name)
fruit = ("apple", "banana", "cherry")
fruit = list(fruit)
fruit.append("mango")
print(fruit)
fruit.remove("banana")
print(fruit)
color = ("ali ahmad")
color = str(color)
color.append("adil")
print(color)
color.remove("ahmad")
print(color)